### ISSUE TITLE
Convert functionality to mod instead of block (paid development work opportunity)

### ISSUE THREAD

**Issue by rolandsherwood2** [Kylegoslin/moodle-block_signinsheet#11]
Hi. We really like this plugin; however, ideally we'd be looking for its functionality to be made available to users via a mod module rather than a block (our students and teachers are heavy Moodle app users and blocks obviously are not an option there). Accordingly, please could I ask if you would be open to the possibility of converting the plugin - and, if so, what the development costs involved might be, as well as preferred methods of payment. Many thanks.

**Comment by Kylegoslin** [comment]
Please email: kylegoslin@gmail.com
