### ISSUE TITLE
Plugin block_signinsheet does not declare valid $plugin->component in its version.php.

### ISSUE THREAD

**Issue by nitro2010** [Kylegoslin/moodle-block_signinsheet#4]
Hello,

Please update your plugin for Moodle v3.0

While installating I get errors [all text with debugging option on]:

Plugin block_signinsheet does not declare valid $plugin->component in its version.php.
line 328 of /lib/classes/plugin_manager.php: call to debugging()
line 348 of /lib/classes/plugin_manager.php: call to core_plugin_manager->load_present_plugins()
line 217 of /lib/classes/plugininfo/base.php: call to core_plugin_manager->get_present_plugins()
line 143 of /lib/classes/plugininfo/base.php: call to core\plugininfo\base->load_disk_version()
line 97 of /lib/classes/plugininfo/base.php: call to core\plugininfo\base::make_plugin_instance()
line 408 of /lib/classes/plugin_manager.php: call to core\plugininfo\base::get_plugins()
line 368 of /lib/classes/plugin_manager.php: call to core_plugin_manager->get_plugins_of_type()
line 442 of /lib/classes/update/checker.php: call to core_plugin_manager->get_plugins()
line 459 of /lib/classes/update/checker.php: call to core\update\checker->load_current_environment()
line 239 of /lib/classes/update/checker.php: call to core\update\checker->prepare_request_params()
line 124 of /lib/classes/update/checker.php: call to core\update\checker->get_response()
line 542 of /admin/index.php: call to core\update\checker->fetch()
Plugin block_slider does not declare valid $plugin->component in its version.php.

**Comment by gemguardian** [comment]
just wondering if there's a planning for updating to Moodle 3.0 - maybe through a contribution?

**Comment by nitro2010** [comment]
enough if author accept pull request: https://github.com/Kylegoslin/moodle-block_signinsheet/pull/5

**Comment by danielmcsweeney** [comment]
Hi apologies all, Moodle 3 has not been a priority as my institution is running on 2.9. Im migrating these and other plugins to Moodle 3 in the coming weeks.

**Comment by Kylegoslin** [comment]
fixed.
